name: Bug Report
description: Create a report to help us improve the project.
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: "**Title**: [BUG]"
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: A clear and concise description of what actually happens (if different from expected).
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots or logs to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: 
        - Python version: 
        - Project version: 
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      placeholder: Add any other context about the problem, such as recent changes, configurations, or similar issues.
    validations:
      required: false
